[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200


; 🟢 สั่งให้ PlatformIO ดาวน์โหลดไลบรารีที่โค้ด ESP32 ของเราต้องใช้แบบอัตโนมัติ
lib_deps = 
	bblanchon/ArduinoJson @ ^6.21.5
	bogde/HX711 @ ^0.7.5
	knolleary/PubSubClient @ ^2.8